name: Tests
on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      actions: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Run Tests
        id: test_run
        run: npm test
        shell: bash
        
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml
          
      - name: Process Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results
          path: test-results.xml
          reporter: java-junit
          fail-on-error: false
